name: Build

on:
  - push
      # branches: [main, development]
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest]
        os: [macOS-latest]
        #python-version: ['3.6']
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --use-pep517 -e .
    - name: coverall
      run: |
        pip install coveralls
        pip install pytest-cover
    - name: run pytest
      run: |
        py.test tods/tests/ --cov=tods
        coveralls
    - name: codecov
      uses: codecov/codecov-action@v1
